config/routes.rb
Kecamatan::Application.routes.draw do

  resources :dashboards, only: [:index]
  resources :users
  resources :sessions
  resources :tabulars do
    collection do
      get :general_display
      put :update_all
    end
  end
  resources :profile, :only => [:index] do
    collection do
      put :modify
      get :edit_password
      put :save_password
    end
  end
  resources :data_sources do
    collection do
      get :export
    end
    member do
      put :set_default
    end
  end

  namespace :admin do
    resources :users
    resources :dashboards, :only => [:index]
    resources :profile, :only => [:index] do
      collection do
        put :modify
        get :edit_password
        put :save_password
      end
    end
    resources :master_tabulars do
      collection do
        post :generate_layout
      end
    end
    resources :tabulars do
      collection do
        get :general_display
        put :update_all
        put :copy_from_year
      end
      member do
        post :import
        get :export
      end
    end
    resources :data_sources do
      collection do
        get :export
      end
      member do
        put :set_default
      end
    end
    resources :histories, :only => [:index, :create]
  end

  root :to => 'pages#index'

end

app/models/tabular.rb
class Tabular < ActiveRecord::Base
  #--
  # constants
  KIND_OPTIONS = ['parent','child']
  #++

  #--
  # requires
  has_ancestry cache_depth: true
  #++

  #--
  # includes
  #++

  #--
  # attribute
  attr_accessible :name, :user_id, :total, :data_source_id, :year, :ancestry,
    :ancestry_depth, :parent_id, :file
  #++

  #--
  # extra capabilities
  mount_uploader :file, FileExportUploader
  #++

  #--
  # belongs_to
  belongs_to :user
  belongs_to :unit
  belongs_to :data_source
  #++

  #--
  # has_one
  #++

  #--
  # has_many
  #++

  #--
  # accepts_nested_attributes_for
  #++

  #--
  # validations
  validates :name, presence: {message: Flash.required_presence}
  #++

  #--
  # callback
  #++

  #--
  # scopes
  scope :by_year_and_user_id, lambda {
    |year, user_id| where(['year = ? AND user_id = ?', year, user_id])
  }
  #++

  #--
  # other definition such as alias_method
  delegate :name, :id, to: :user, prefix: true
  delegate :name, to: :unit, prefix: true
  delegate :name, to: :data_source, prefix: true
  #++

  #--
  # public class methods
  def self.search(params)
    return scoped unless params
    conditions = []
    params.each do |key, value|
      if value.present?
        case key
        when ""
        else
          conditions << "#{key} = '#{value}'"
        end
      end
    end
    where(conditions.join(" AND "))
  end

  # Created by [muhamadakbarbw@gmail.com] at May 11 2013,
  # Copy tabular from last year
  def self.copy_from_year(year, user)
    tabulars = self.by_year_and_user_id(year, user.id)
    tabulars.each do |tabular|
      current_tabulars = self.by_year_and_user_id(Date.today.year, user.id)
      current_tabulars.each do |current_tabular|
        if current_tabular.name == tabular.name
          current_tabular.update_attribute(:total, tabular.total)
        end
      end
    end
  end
  #++

  #--
  # public instance methods
  #++

  private
  #--
  # private class methods
  #++

  #--
  # private instance methods
  #++

  protected
  #--
  # protected class methods
  #++

  #--
  # protected instance methods
  #++
end

app/controllers/admin/tabulars_controller.rb
class Admin::TabularsController < ApplicationController
  before_filter :require_admin_login
  before_filter :find_tabular, only: [:edit, :update, :destroy, :add_child, :show,
    :import, :export]
  before_filter :prepare_data, only: [:new, :create, :edit, :update]
  before_filter :validate_excel, only: [:import]
  layout "admin"

  def index
    @user_options = GlobalClass.options_select(User)
    @tabulars = Tabular.search(params[:tabular]).select([:year, :user_id]).joins(:user).group([:year, :user_id]).paginate(per_page: DEFAULT_PER_PAGE, page: params[:page])
  end

  def show
    @user_tabulars = @tabular.descendants
    respond_to do |format|
      format.html
    end
  end

  # Created by [muhamadakbarbw@gmail.com] at May 9 2013,
  # general display
  def general_display
    @tabulars = Tabular.where(['ancestry_depth IN (?) AND user_id = ? AND year = ?', [0,1], params[:user_id], params[:year]])
  end

  # Created by [muhamadakbarbw@gmail.com] at May 9 2013,
  # update all tabular
  def update_all
    params[:tabular].each do |key, val|
      if val[:val] != val[:old_val]
        tabular = Tabular.find_by_id(key)
        tabular.update_attribute(:total, val[:val])
      end
    end
    flash[:notice] = Flash.succcessfully_updated
    redirect_to admin_tabulars_path
  end

  # Created by [muhamadakbarbw@gmail.com] at May 11 2013,
  # copy from last year.
  def copy_from_year
    Tabular.copy_from_year(params[:tabular][:year], current_user)
    flash[:notice] = Flash.succcessfully_updated
    redirect_to admin_tabulars_path
  end

  # Created by [muhamadakbarbw@gmail.com] at May 20 2013,
  # export excel
  def export
    file = Export.export({object: @tabular, year: @tabular.year, user: @tabular.user})
    send_file file[:filepath]
  end

  # Created by: [muhamadakbarbw@gmail.com] at May 19 2013,
  # title: Import excel from user by data tabular
  # input: excel, year, user, total
  # process: get and update the tabular by input
  # output : total will be update with same format excel and database
  def import
    result = Export.upload_excel(params[:tabular], false)
    if result[:status]
      Export.import_value({object: @tabular, path: result[:path], user: @tabular.user})
      flash[:notice] = Flash.successfully_imported
      redirect_to admin_tabular_path(@tabular)
    else
      flash.now[:error] = Flash.failed_imported
      redirect_to admin_tabular_path(@tabular)
    end
  end

  private
  def find_tabular
    @tabular = Tabular.find_by_id(params[:id])
    if @tabular.nil?
      flash[:error] = Flash.data_not_found
      redirect_to admin_tabulars_path
    end
  end

  def prepare_data
    @unit_options = GlobalClass.options_select(Unit)
    @options_data_sources = GlobalClass.options_select(DataSource) # change to data_source_options
    @tabular_options = GlobalClass.options_select(Tabular)
  end

  def validate_excel
    if params[:tabular].blank?
      flash.now[:error] = Flash.failed_imported
      redirect_to admin_tabular_path(@tabular)
    end
  end
end

app/controllers/tabulars_controller.rb
class TabularsController < ApplicationController
  before_filter :require_user_login
  before_filter :find_tabular, only: [:edit, :update, :destroy, :add_child, :show]
  before_filter :prepare_data, only: [:new, :create, :edit, :update]
  layout "user"

  def index
    @tabulars = Tabular.roots.where(['user_id = ? AND year = ?', current_user.id, "#{Date.today.year}"])
  end

  def destroy
    if @tabular.destroy
      record_history("#{current_user.name} menghapus data tabular dengan nama #{@tabular.name}")
      flash[:notice] = Flash.successfully_deleted
      redirect_to tabulars_path
    end
  end

  def show
    @user_tabulars = @tabular.descendants
  end

  # Created by [muhamadakbarbw@gmail.com] at May 9 2013,
  # update all tabular
  def update_all
    params[:tabular].each do |key, val|
      if val[:val] != val[:old_val]
        tabular = Tabular.find_by_id(key)
        tabular.update_attribute(:total, val[:val])
      end
    end
    flash[:notice] = Flash.succcessfully_updated
    redirect_to tabulars_path
  end

  private
  def find_tabular
    @tabular = Tabular.find_by_id(params[:id])
    if @tabular.nil?
      flash[:error] = Flash.data_not_found
      redirect_to tabulars_path
    end
  end

  def prepare_data
    @options_data_sources = GlobalClass.options_select(DataSource) # change to data_source_options
    @tabular_options = GlobalClass.options_select(Tabular)
  end
end

app/helpers/admin/tabulars_helper.rb
module Admin::TabularsHelper
end

app/helpers/tabulars_helper.rb
module TabularsHelper
end

app/views/admin/tabulars/_form.html.erb
<div id="support-data" style="width:500px;height:auto;">
  <div class="row-fluid">
    <div class="span6">
      <div class="block">
        <div class="head">
          <h2><%= title %></h2>
        </div>
        <div class="data-fluid">
          <%= form_for tabular, :url => url, :remote => true do |f| %>
            <div class="row-form">
              <div class="span3"><%= f.label :parent_sub %></div>
              <div class="span9"><%= select(:tabular, :parent_id, tabular_options) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :kind %></div>
              <div class="span9"><%= f.select :kind, Tabular::KIND_OPTIONS ,:prompt => PROMPT_OPTION %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :name %></div>
              <div class="span9"><%= f.text_field :name, :placeholder => "Isilah data nama tabular" %></div>
              <div class="span9"><%= display_error(tabular, :name) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :unit %></div>
              <div class="span9"><%= select(:tabular, :unit_id, unit_options) %></div>
              <div class="span9"><%= display_error(tabular, :unit_id) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :nilai %></div>
              <div class="span9"><%= f.text_field :total, :placeholder => "Isilah data nilai tabular" %></div>
              <div class="span9"><%= display_error(tabular, :total) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :data_sources %></div>
              <div class="span9"><%= select(:tabular, :data_source_id, options_data_sources) %></div>
              <div class="span9"><%= display_error(tabular, :data_source_id) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.submit name_button, :class => "btn" %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tabulars/_tabular.xls.erb
<% padding = (tabular.ancestry_depth) * 15 %>
<tr>
  <td>
    <%= "#{(" " * padding)} #{(tabular.name)}" %>
  </td>
  <td>
    <%= tabular.total %>
  </td>
  <td>
    <%= tabular.unit_name rescue "-" %>
  </td>
</tr>

app/views/admin/tabulars/create.js.erb
$(document).ready(function(){
  $.ajax({
    beforeSend:function(respond){
    },
    complete:function(respond){
      <%- if @tabular.errors.any? %>
        $('#support-data').html('<%= escape_javascript(
          render('/admin/tabulars/form', :url => admin_tabulars_path, :tabular => @tabular,
            :unit_options => @unit_options, :options_data_sources => @options_data_sources,
            :tabular_options => @tabular_options, :title => "Tambah Tabular Data",
            :name_button => "Simpan"))
          %>');
      <% else %>
        parent.$.fancybox.close();
      <% end %>
    }
  });
});

app/views/admin/tabulars/general_display.html.erb
<div class="content">
  <div class="page-header">
    <div class="icon">
      <span class="ico-layout-7"></span>
    </div>
    <h1>Data Tabular <small>ADMINISTRASI SISTEM INFORMASI PEMBANGUNAN DAERAH</small></h1>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <div class="block">
        <div class="data-fluid">
          <table cellpadding="0" cellspacing="0" width="100%" class="table">
            <thead>
              <tr>
                <th width="50%">
                  Nama Sumber Data
                </th>
                <th width="10%">
                  Value
                </th>
                <th width="10%">
                  Satuan
                </th>
                <th width="25%">
                  Sumber Data
                </th>
              </tr>
            </thead>
            <tbody>
              <%= nested_master_tabulars(@tabulars.arrange(:order => :created_at)) %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tabulars/index.html.erb
<div class="content">
  <div class="page-header">
    <div class="icon">
      <span class="ico-layout-7"></span>
    </div>
    <h1>Kelompok Data <small>ADMINISTRASI SISTEM INFORMASI PEMBANGUNAN DAERAH</small></h1>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <div class="span3">
        <%= form_tag admin_tabulars_path, :method => :get do %>
          <%= label_tag :pilih_kecamatan %>
          <%= select("tabular", :user_id, @user_options) %>
          <%= label_tag :pilih_tahun %>
          <%= select_year(Date.today, {:start_year => 1992, :end_year => 2019}, {:name => "tabular[year]"}) %>
          <%= submit_tag "Cari", :class => "btn" %>
        <% end %>
      </div>
      <div class="block">
        <div class="data-fluid">
          <table cellpadding="0" cellspacing="0" width="100%" class="table">
            <thead>
              <tr>
                <th width="5%">
                  No
                </th>
                <th width="25%">
                  Nama Kecamatan
                </th>
                <th width="25%">
                  Tahun
                </th>
                <th width="25%">
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              <% @tabulars.each_with_index do |tabular, idx| %>
                <tr>
                  <td>
                    <%= params[:page].nil? ? idx + 1 : DEFAULT_PER_PAGE * (params[:page].to_i - 1) + idx + 1 %>
                  </td>
                  <td>
                    <%= tabular.user_name %>
                  </td>
                  <td>
                    <%= tabular.year rescue "-" %>
                  </td>
                  <td>
                    <%= link_to "Lihat", general_display_admin_tabulars_path(:user_id => tabular.user_id, :year => tabular.year) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate(@tabulars) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tabulars/new.html.erb
<%= render "form", :url => admin_tabulars_path, :tabular => @tabular,
  :unit_options => @unit_options, :options_data_sources => @options_data_sources,
  :tabular_options => @tabular_options, :title => "Tambah Sumber Data",
  :name_button => "Simpan"
%>

app/views/admin/tabulars/show.html.erb
<div class="content">
  <div class="page-header">
    <div class="icon">
      <span class="ico-layout-7"></span>
    </div>
    <h1>Kelompok Data <small>ADMINISTRASI SISTEM INFORMASI PEMBANGUNAN DAERAH</small></h1>
  </div>
  <div class="span3">
    <p><strong>Kecamatan:</strong> <%= @tabular.user_name %></p>
    <p><strong>Tahun:</strong> <%= @tabular.year %></p>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <div class="span3">
        <%= form_tag copy_from_year_admin_tabulars_path, :method => :put do %>
          <%= label_tag :pilih_tahun %>
          <%= select_year(Date.today, {:start_year => 1992, :end_year => Date.today.year - 1}, {:name => "tabular[year]"}) %>
          <%= submit_tag "Copy", :class => "btn" %>
        <% end %>
      </div>
      <div class="span3">
        <%= link_to "Edit", "#", :class => "btn edit-tabular" %>
        <%= link_to "Export", export_admin_tabular_path(@tabular), :class => "btn" %>
        <%= form_tag import_admin_tabular_path(@tabular), :method => :post, :multipart => true do %>
          <%= file_field_tag "tabular[file]" %>
          <%= submit_tag "Import", :class => "btn" %>
        <% end %>
      </div>
      <div class="block">
        <div class="data-fluid">
          <table cellpadding="0" cellspacing="0" width="100%" class="table">
            <thead>
              <tr>
                <th width="50%">
                  Nama Sumber Data
                </th>
                <th width="10%">
                  Value
                </th>
                <th width="10%">
                  Satuan
                </th>
                <th width="25%">
                  Sumber Data
                </th>
              </tr>
            </thead>
            <tbody>
              <%= form_for @tabular, :url => update_all_admin_tabulars_path, :html => {:method => :put} do |f| %>
                <%= nested_tabulars(@user_tabulars.arrange(:order => :created_at), :f => f) %>
                <%= f.submit :class => "btn update-all-btn-tabular" %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tabulars/show.xls.erb
<table>
  <tbody>
    <tr>
      <td>Kecamatan</td>
      <td><%= @tabular.user_name %></td>
    </tr>
    <tr>
      <td>Jenis Data</td>
      <td><%= @tabular.name %></td>
    </tr>
    <tr>
      <td>Tahun</td>
      <td><%= @tabular.year %></td>
    </tr>
    <tr>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>
        Nama Sumber Data
      </th>
      <th>
        Value
      </th>
      <th>
        Satuan
      </th>
    </tr>
  </thead>
  <tbody>
    <%= nested_master_tabulars(@user_tabulars.arrange(:order => :created_at)) %>
  </tbody>
</table>