config/routes.rb
Kecamatan::Application.routes.draw do

  resources :dashboards, only: [:index]
  resources :users
  resources :sessions
  resources :tabulars do
    collection do
      get :general_display
      put :update_all
    end
  end
  resources :profile, :only => [:index] do
    collection do
      put :modify
      get :edit_password
      put :save_password
    end
  end
  resources :data_sources do
    collection do
      get :export
    end
    member do
      put :set_default
    end
  end

  namespace :admin do
    resources :users
    resources :dashboards, :only => [:index]
    resources :profile, :only => [:index] do
      collection do
        put :modify
        get :edit_password
        put :save_password
      end
    end
    resources :master_tabulars do
      collection do
        post :generate_layout
      end
    end
    resources :tabulars do
      collection do
        get :general_display
        put :update_all
        put :copy_from_year
      end
      member do
        post :import
        get :export
      end
    end
    resources :data_sources do
      collection do
        get :export
      end
      member do
        put :set_default
      end
    end
    resources :histories, :only => [:index, :create]
  end

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  #--
  # constants
  #++

  #--
  # requires
  #++

  #--
  # includes
  #++

  #--
  # attribute
  attr_protected :password, :password_confirmation, :email
  attr_accessible :email, :password, :password_confirmation, :name, :telephone,
    :fax, :website, :old_password, :address, :role_id, :image_user_cache,
    :image_user, :remove_image_user
  attr_accessor :password, :old_password, :image_user_cache
  #++

  #--
  # extra capabilities
  mount_uploader :image_user, ImageUserUploader
  #++

  #--
  # belongs_to
  belongs_to :role
  #++

  #--
  # has_one
  #++

  #--
  # has_many
  has_many :histories
  has_many :data_sources
  #++

  #--
  # accepts_nested_attributes_for
  #++

  #--
  # validations
  validates :name, presence: {message: Flash.required_presence},
    uniqueness: {message: Flash.required_uniqueness}
  validates :role_id, presence: {message: Flash.required_presence}
  validates :password, presence: {on: :create, message: Flash.required_presence},
    confirmation: true
  validates :email, presence: {message: Flash.required_presence},
    uniqueness: {message: Flash.required_uniqueness}
  #++

  #--
  # callback
  before_save :encrypt_password
  #++

  #--
  # scopes
  #++

  #--
  # other definition such as alias_method
  delegate :name, to: :role, prefix: true
  #++

  #--
  # public class methods
  class << self
    Role::ROLES.each do |role|
      define_method "all_#{role}" do
        where(['role_id = ? AND remove = ?', Role.find_by_name(role).id, false])
      end
    end
  end

  # Created by [muhamadakbarbw@gmail.com] at May 10 2013,
  # search user.
  def self.search(params)
    return self.all_user unless params
    conditions = []
    params.each do |key, value|
      if value.present?
        case key
        when "search"
          conditions << "name LIKE '%#{value}%'"
        else
          conditions << key +"="+ value
        end
      end
    end
    self.all_user.where(conditions.join(" AND "))
  end

  # Created by [muhamadakbarbw@gmail.com] at April 16 2013,
  # to check authentication user
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  #++

  #--
  # public instance methods
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  # Created by [muhamadakbarbw@gmail.com] at April 16 2013,
  # to get return true role
  # for example: admin?
  Role::ROLES.each do |role|
    define_method "#{role}?" do
      self.role.name == role
    end
  end

  # Created by [muhamadakbarbw@gmail.com] at May 11 2013,
  # Move to trash when user was deleted
  # for example: admin?
  def move_to_trash
    self.update_attribute(:remove, true)
  end
  #++

  private
  #--
  # private class methods
  #++

  #--
  # private instance methods
  def validate_password_old
    errors[:old_password] << Flash.required_presence
  end
  #++

  protected
  #--
  # protected class methods
  #++

  #--
  # protected instance methods
  #++
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :require_admin_login
  before_filter :find_user, only: [:edit, :update, :destroy]
  layout "admin"

  def index
    @users = User.search(params[:user]).paginate(per_page: DEFAULT_PER_PAGE, page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = Flash.successfully_created
      redirect_to admin_users_path
    else
      flash.now[:error] = Flash.failed_created
      render "new"
    end
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = Flash.succcessfully_updated
      redirect_to admin_users_path
    else
      flash[:error] = Flash.failed_updated
      render "edit"
    end
  end

  def destroy
    if @user.move_to_trash
      flash[:notice] = Flash.successfully_deleted
      redirect_to admin_users_path
    end
  end

  def show
  end

  private
  def find_user
    @user = User.find_by_id(params[:id])
    if @user.nil?
      flash[:error] = Flash.not_found
      redirect_to admin_users_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/user/_navigation.html.erb
<ul class="navigation">
  <li>
    <%= link_to dashboards_path, :class => "button" do %>
      <div class="icon">
        <span class="ico-monitor"></span>
      </div>
      <div class="name">Dashboard</div>
    <% end %>
  </li>
  <li>
    <%= link_to "#", :class => "button yellow" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-cog-2"></span>
      </div>
      <div class="name">Nilai Profile</div>
    <% end %>
    <ul class="sub">
      <li><%= link_to "Data Tabular", tabulars_path %></li>
    </ul>
  </li>
  <li>
    <%= link_to data_sources_path, :class => "button green" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-pen-2"></span>
      </div>
      <div class="name">Sumber Data</div>
    <% end %>
  </li>
  <li>
    <%= link_to edit_password_profile_index_path, :class => "button red" do %>
      <div class="icon">
        <span class="ico-chart-4"></span>
      </div>
      <div class="name">Ganti Password</div>
    <% end %>
  </li>
  <li>
    <%= link_to profile_index_path, :class => "button dblue" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-layout-7"></span>
      </div>
      <div class="name">Edit Kontak</div>
    <% end %>
  </li>
  <li>
    <div class="user">
      <%= current_user.image_user? ? image_tag(current_user.image_user_url(:thumb), :align => "left", :size => '32x32') : image_tag("avatar.gif", :size => '32x32', :align => "left") %>
      <a href="#" class="name">
        <span><%= current_user.name %></span>
        <span class="sm"><%= current_user.role.name %></span>
      </a>
    </div>
    <div class="buttons">
      <div class="sbutton green navButton">
        <a href="#"><span class="ico-align-justify"></span></a>
      </div>
      <div class="sbutton blue">
        <a href="#"><span class="ico-cogs"></span></a>
        <div class="popup">
          <div class="arrow"></div>
          <div class="row-fluid">
            <div class="row-form">
              <div class="span12"><strong>SETTINGS</strong></div>
            </div>
            <div class="row-form">
              <div class="span4">Navigation:</div>
              <div class="span8"><input type="radio" class="cNav" name="cNavButton" value="default"/> Default <input type="radio" class="cNav" name="cNavButton" value="bordered"/> Bordered</div>
            </div>
            <div class="row-form">
              <div class="span4">Content:</div>
              <div class="span8"><input type="radio" class="cCont" name="cContent" value=""/> Responsive <input type="radio" class="cCont" name="cContent" value="fixed"/> Fixed</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </li>
</ul>

app/views/shared/user/_sidebar.html.erb
<div class="sidebar">
  <div class="top">
    <a href="#" class="logo"></a>
  </div>
  <div class="nContainer">
    <ul class="navigation bordered">
      <li class="active"><%= link_to "Dashboard", admin_dashboards_path, :class => "blblue" %></li>
      <li>
        <%= link_to "Sign Out", session_path(current_user), :method => :delete, :class => "blorange" %>
      </li>
    </ul>
    <a class="close">
      <span class="ico-remove"></span>
    </a>
  </div>
  <div class="widget">
    <div class="datepicker"></div>
  </div>
</div>