config/routes.rb
Kecamatan::Application.routes.draw do

  resources :dashboards, only: [:index]
  resources :users
  resources :sessions
  resources :tabulars do
    collection do
      get :general_display
      put :update_all
    end
  end
  resources :profile, :only => [:index] do
    collection do
      put :modify
      get :edit_password
      put :save_password
    end
  end
  resources :data_sources do
    collection do
      get :export
    end
    member do
      put :set_default
    end
  end

  namespace :admin do
    resources :users
    resources :dashboards, :only => [:index]
    resources :profile, :only => [:index] do
      collection do
        put :modify
        get :edit_password
        put :save_password
      end
    end
    resources :master_tabulars do
      collection do
        post :generate_layout
      end
    end
    resources :tabulars do
      collection do
        get :general_display
        put :update_all
        put :copy_from_year
      end
      member do
        post :import
        get :export
      end
    end
    resources :data_sources do
      collection do
        get :export
      end
      member do
        put :set_default
      end
    end
    resources :histories, :only => [:index, :create]
  end

  root :to => 'pages#index'

end

app/views/shared/_confirmation.html.erb
<div id="<%= cfrm_id %>" style="width:280px;height:auto;">
  <h3>Confirmation</h3>
  <p><%= msg %></p>
  <div>
    <input type="submit" id="confirm_button" value="Yes"/>
    <span class="cancel-confirm">No</span>
    <div class="clear"></div>
  </div>
</div>

app/views/shared/_flash_message.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= set_flash_name(name) %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="login">
  <div class="page-header">
    <div class="icon">
      <span class="ico-arrow-right"></span>
    </div>
    <h1>Sign In <small>ADMIN PANEL</small></h1>
  </div>
  <%= form_tag sessions_path, :autocomplete => "off" do %>
  <div class="row-fluid">
    <div class="row-form">
      <div class="span12">
        <%= text_field_tag :email, nil, :placeholder => "email" %>
      </div>
    </div>
    <div class="row-form">
      <div class="span12">
        <%= password_field_tag :password, nil, :placeholder => "password" %>
      </div>
    </div>
    <div class="row-form">
      <div class="span12">
        <button class="btn">Sign in <span class="icon-arrow-next icon-white"></span></button>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_navigation.html.erb
<ul class="navigation">
  <li>
    <a href="#" class="button">
      <div class="icon">
        <span class="ico-monitor"></span>
      </div>
      <div class="name">Dashboard</div>
    </a>
  </li>
  <li>
    <%= link_to admin_tabulars_path, :class => "button yellow" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-cog-2"></span>
      </div>
      <div class="name">Nilai Profile</div>
    <% end %>
    <ul class="sub">
      <li><%= link_to "Manage Data Tabular", admin_tabulars_path %></li>
      <li><a href="#">Manage Data Tabular Kecamatan</a></li>
    </ul>
  </li>
  <li>
    <%= link_to admin_data_sources_path, :class => "button green" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-pen-2"></span>
      </div>
      <div class="name">Sumber Data</div>
    <% end %>
    <ul class="sub">
      <li><a href="#">Elements</a></li>
      <li><a href="#">Validation</a></li>
      <li><a href="#">Grid</a></li>
      <li><a href="#">Editors</a></li>
      <li><a href="#">Wizard</a></li>
    </ul>
  </li>
  <li>
    <%= link_to edit_password_admin_profile_index_path, :class => "button red" do %>
      <div class="icon">
        <span class="ico-chart-4"></span>
      </div>
      <div class="name">Ganti Password</div>
    <% end %>
  </li>
  <li>
    <%= link_to admin_profile_index_path, :class => "button dblue" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-layout-7"></span>
      </div>
      <div class="name">Edit Kontak</div>
    <% end %>
    <ul class="sub">
      <li><a href="#">Simple</a></li>
      <li><a href="#">Dynamic</a></li>
    </ul>
  </li>
  <li>
    <a href="#" class="button purple">
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-box"></span>
      </div>
      <div class="name">Keterisian Data</div>
    </a>
    <ul class="sub">
      <li><a href="#">FAQ</a></li>
      <li><a href="#">Login</a></li>
    </ul>
  </li>
  <li>
    <%= link_to admin_histories_path, :class => "button orange" do %>
      <div class="arrow"></div>
      <div class="icon">
        <span class="ico-cloud"></span>
      </div>
      <div class="name">Histories</div>
    <% end %>
    <ul class="sub">
      <li><a href="#">File handling</a></li>
      <li><a href="#">Images</a></li>
      <li><a href="#">Typography</a></li>
      <li><a href="#">Error 404</a></li>
    </ul>
  </li>
  <li>
    <div class="user">
      <img src="/assets/examples/users/dmitry_m.jpg" align="left"/>
      <a href="#" class="name">
        <span>Dmitry Ivaniuk</span>
        <span class="sm">Administrator</span>
      </a>
    </div>
    <div class="buttons">
      <div class="sbutton green navButton">
        <a href="#"><span class="ico-align-justify"></span></a>
      </div>
      <div class="sbutton blue">
        <a href="#"><span class="ico-cogs"></span></a>
        <div class="popup">
          <div class="arrow"></div>
          <div class="row-fluid">
            <div class="row-form">
              <div class="span12"><strong>SETTINGS</strong></div>
            </div>
            <div class="row-form">
              <div class="span4">Navigation:</div>
              <div class="span8"><input type="radio" class="cNav" name="cNavButton" value="default"/> Default <input type="radio" class="cNav" name="cNavButton" value="bordered"/> Bordered</div>
            </div>
            <div class="row-form">
              <div class="span4">Content:</div>
              <div class="span8"><input type="radio" class="cCont" name="cContent" value=""/> Responsive <input type="radio" class="cCont" name="cContent" value="fixed"/> Fixed</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </li>
</ul>