config/routes.rb
Kecamatan::Application.routes.draw do

  resources :dashboards, only: [:index]
  resources :users
  resources :sessions
  resources :tabulars do
    collection do
      get :general_display
      put :update_all
    end
  end
  resources :profile, :only => [:index] do
    collection do
      put :modify
      get :edit_password
      put :save_password
    end
  end
  resources :data_sources do
    collection do
      get :export
    end
    member do
      put :set_default
    end
  end

  namespace :admin do
    resources :users
    resources :dashboards, :only => [:index]
    resources :profile, :only => [:index] do
      collection do
        put :modify
        get :edit_password
        put :save_password
      end
    end
    resources :master_tabulars do
      collection do
        post :generate_layout
      end
    end
    resources :tabulars do
      collection do
        get :general_display
        put :update_all
        put :copy_from_year
      end
      member do
        post :import
        get :export
      end
    end
    resources :data_sources do
      collection do
        get :export
      end
      member do
        put :set_default
      end
    end
    resources :histories, :only => [:index, :create]
  end

  root :to => 'pages#index'

end

app/models/data_source.rb
class DataSource < ActiveRecord::Base
  #--
  # constants
  #++

  #--
  # requires
  #++

  #--
  # includes
  #++

  #--
  # attribute
  attr_accessible :name, :telephone, :address, :user_id, :default
  #++

  #--
  # extra capabilities
  #++

  #--
  # belongs_to
  belongs_to :user
  #++

  #--
  # has_one
  #++

  #--
  # has_many
  has_many :tabulars
  #++

  #--
  # accepts_nested_attributes_for
  #++

  #--
  # validations
  validates :name, presence: {message: Flash.required_presence}
  validates :telephone, presence: {message: Flash.required_presence}
  validates :address, presence: {message: Flash.required_presence}
  #++

  #--
  # callback
  #++

  #--
  # scopes
  #++

  #--
  # other definition such as alias_method
  delegate :name, to: :user, prefix: true
  #++

  #--
  # public class methods
  def self.search(params)
    return scoped unless params
    conditions = []
    params.each do |key, value|
      if value.present?
        case key
        when "search"
          conditions << "name LIKE '%#{value}%'"
        else
          conditions << key +"="+ value
        end
      end
    end
    where(conditions.join(" AND "))
  end

  def self.get_data
    all.map{|c| [c.name, c.telephone, c.address, c.user_name]}
  end

  # Created by [muhamadakbarbw@gmail.com] at May 11 2013,
  # set default data source by user
  def self.set_default(data_source)
    data_source_default = DataSource.find_by_default_and_user_id(true, data_source.user_id)
    if data_source_default.present?
      if data_source.id != data_source_default.id
        data_source.update_attribute(:default, true)
        data_source_default.update_attribute(:default, false)
      end
    else
      data_source.update_attribute(:default, true)
    end
  end
  #++

  #--
  # public instance methods
  #++

  private
  #--
  # private class methods
  #++

  #--
  # private instance methods
  #++

  protected
  #--
  # protected class methods
  #++

  #--
  # protected instance methods
  #++
end

app/controllers/admin/data_sources_controller.rb
class Admin::DataSourcesController < ApplicationController
  before_filter :require_admin_login
  before_filter :find_data_source, only: [:edit, :update, :destroy, :set_default]
  layout "admin"

  def index
    @data_sources = DataSource.search(params[:data_source]).paginate(per_page: DEFAULT_PER_PAGE, page: params[:page])
    @user_options = GlobalClass.options_select(User)
  end

  def new
    @user_options = GlobalClass.options_select(User)
    @data_source = DataSource.new
    render layout: false
  end

  def create
    @data_source = DataSource.new(params[:data_source])
    respond_to do |format|
      if @data_source.save
        record_history("#{current_user.name} membuat data tabular dengan nama : #{@data_source.name}")
        flash[:notice] = Flash.successfully_created
        format.html { redirect_to admin_data_sources_path }
        format.js
      else
        flash[:error] = Flash.failed_created
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
    @user_options = GlobalClass.options_select(User)
    render layout: false
  end

  def update
    respond_to do |format|
      if @data_source.update_attributes(params[:data_source])
        record_history("#{current_user.name} mengedit sumber data pada : #{@data_source.name}")
        flash[:notice] = Flash.succcessfully_updated
        format.html { redirect_to admin_data_sources_path }
        format.js
      else
        flash[:error] = Flash.failed_updated
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    if @data_source.destroy
      record_history("#{current_user.name} menghapus sumber data : #{@data_source.name}")
      flash[:notice] = Flash.successfully_deleted
      redirect_to admin_data_sources_path
    end
  end

  def show
  end

  def export
    file = Export.generate({data: DataSource.get_data, filename: "Sumber Data", columns: DataSource.column_names - ["updated_at", "created_at"]})
    send_file file[:filepath]
  end

  def set_default
    data_source_default = DataSource.find_by_default(true)
    if data_source_default.present?
      if @data_source.id != data_source_default.id
        @data_source.update_attribute(:default, true)
        data_source_default.update_attribute(:default, false)
      end
    else
      @data_source.update_attribute(:default, true)
    end
    flash[:notice] = Flash.succcessfully_updated
    redirect_to admin_data_sources_path
  end

  private
  def find_data_source
    @data_source = DataSource.find_by_id(params[:id])
    if @data_source.nil?
      flash[:error] = Flash.not_found
      redirect_to admin_data_sources_path
    end
  end
end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_filter :require_user_login
  before_filter :find_data_source, only: [:edit, :update, :destroy, :set_default]
  layout "user"

  def index
    @data_sources = current_user.data_sources.search(params[:data_source])
    .paginate(per_page: DEFAULT_PER_PAGE, page: params[:page])
  end

  def new
    @data_source = DataSource.new
  end

  def create
    @data_source = current_user.data_sources.build(params[:data_source])
    respond_to do |format|
      if @data_source.save
        record_history("#{current_user.name} membuat data tabular dengan nama : #{@data_source.name}")
        flash[:notice] = Flash.successfully_created
        format.html { redirect_to data_sources_path }
        format.js
      else
        flash[:error] = Flash.failed_created
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @data_source.update_attributes(params[:data_source])
        record_history("#{current_user.name} mengedit sumber data pada : #{@data_source.name}")
        flash[:notice] = Flash.succcessfully_updated
        format.html { redirect_to data_sources_path }
        format.js
      else
        flash[:error] = Flash.failed_updated
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    if @data_source.destroy
      record_history("#{current_user.name} menghapus sumber data : #{@data_source.name}")
      flash[:notice] = Flash.successfully_deleted
      redirect_to data_sources_path
    end
  end

  def show
  end

  def export
    file = Export.generate({data: DataSource.get_data, filename: "Sumber Data", columns: DataSource.column_names - ["updated_at", "created_at"]})
    send_file file[:filepath]
  end

  def set_default
    DataSource.set_default(@data_source)
    flash[:notice] = Flash.succcessfully_updated
    redirect_to data_sources_path
  end

  private
  def find_data_source
    @data_source = DataSource.find_by_id(params[:id])
    if @data_source.nil?
      flash[:error] = Flash.not_found
      redirect_to data_sources_path
    end
  end
end

app/helpers/admin/data_sources_helper.rb
module Admin::DataSourcesHelper
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/admin/data_sources/_form.html.erb
<div id="support-data-source" style="width:500px;height:auto;">
  <div class="row-fluid">
    <div class="span6">
      <div class="block">
        <div class="head">
          <h2><%= title %></h2>
        </div>
        <div class="data-fluid">
          <%= form_for data_source, :url => url, :remote => true do |f| %>
            <div class="row-form">
              <div class="span3"><%= f.label :name %></div>
              <div class="span9"><%= f.text_field :name, :placeholder => "Isilah data nama sumber data" %></div>
              <div class="span9"><%= display_error(data_source, :name) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :telephone %></div>
              <div class="span9"><%= f.text_field :telephone, :placeholder => "Isilah telephone sumber data" %></div>
              <div class="span9"><%= display_error(data_source, :telephone) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :address %></div>
              <div class="span9"><%= f.text_field :address, :placeholder => "Isilah alamat sumber data" %></div>
              <div class="span9"><%= display_error(data_source, :address) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.label :kecamatan %></div>
              <div class="span9"><%= select(:data_source, :user_id, @user_options) %></div>
              <div class="span9"><%= display_error(data_source, :address) %></div>
            </div>
            <div class="row-form">
              <div class="span3"><%= f.submit name_button, :class => "btn" %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/data_sources/create.js.erb
$(document).ready(function(){
  $.ajax({
    beforeSend:function(respond){
    },
    complete:function(respond){
      <%- if @data_source.errors.any? %>
        $('#support-data-source').html('<%= escape_javascript(
          render('/admin/data_sources/form', :url => admin_data_sources_path,
            :data_source => @data_source, :title => "Tambah Sumber Data",
            :name_button => "Simpan")) %>');
      <% else %>
        parent.$.fancybox.close();
      <% end %>
    }
  });
});

app/views/admin/data_sources/edit.html.erb
<%= render "form", :url => admin_data_source_path(@data_source), :data_source => @data_source, :title => "Ubah Sumber Data", :name_button => "Update" %>

app/views/admin/data_sources/index.html.erb
<div class="content">
  <div class="page-header">
    <div class="icon">
      <span class="ico-layout-7"></span>
    </div>
    <h1>Kelompok Data <small>ADMINISTRASI SISTEM INFORMASI PEMBANGUNAN DAERAH</small></h1>
  </div>
  <%= form_tag admin_data_sources_path, :method => 'get' do %>
    <%= text_field_tag "data_source[search]" %>
    <%= label_tag :pilih_kecamatan %>
    <%= select("data_source", :user_id, @user_options) %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
  <div class="row-fluid">
    <div class="span12">
      <div class="span3">
        <a id="add-data" href="/admin/data_sources/new" class="btn btn-large btn-block btn-warning" type="button">Tambah data tabular</a>
        <%= link_to "Import excle", export_admin_data_sources_path, :class => "btn" %>
      </div>
      <div class="block">
        <div class="data-fluid">
          <table cellpadding="0" cellspacing="0" width="100%" class="table">
            <thead>
              <tr>
                <th width="25%">
                  No
                </th>
                <th width="25%">
                  Nama Sumber Data
                </th>
                <th width="25%">
                  No Telp
                </th>
                <th width="25%">
                  Alamat
                </th>
                <th width="25%">
                  Kecamatan
                </th>
                <th width="25%">
                  Default
                </th>
                <th width="25%">
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              <% @data_sources.each_with_index do |data_source, idx| %>
                <tr>
                  <td>
                    <%= idx + 1 %>
                  </td>
                  <td>
                    <%= link_to data_source.name, admin_data_source_path(data_source) %>
                  </td>
                  <td>
                    <%= data_source.telephone rescue "-" %>
                  </td>
                  <td>
                    <%= data_source.address rescue "-" %>
                  </td>
                  <td>
                    <%= data_source.user_name rescue "-" %>
                  </td>
                  <td>
                    <% unless data_source.default? %>
                      <%= link_to "Set Default", set_default_admin_data_source_path(data_source), :method => :put, :class => "label label-success" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "Edit", edit_admin_data_source_path(data_source), :class => "edit-data", :id => data_source.id %>
                    <%= link_to "Delete", admin_data_source_path(data_source), :method => :delete, :confirm => "Are you sure to delete this?" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate(@data_sources) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/data_sources/new.html.erb
<%= render "form", :url => admin_data_sources_path, :data_source => @data_source, :title => "Tambah Sumber Data", :name_button => "Simpan" %>

app/views/admin/data_sources/update.js.erb
$(document).ready(function(){
  $.ajax({
    beforeSend:function(respond){
    },
    complete:function(respond){
      <%- if @data_source.errors.any? %>
        $('#support-data-source').html('<%= escape_javascript(
          render('/admin/data_sources/form', :url => admin_data_sources_path,
            :data_source => @data_source, :title => "Ubah Sumber Data",
            :name_button => GlobalClass.button_update)) %>');
      <% else %>
        parent.$.fancybox.close();
      <% end %>
    }
  });
});